### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by architlatkar27** [YehLi/xmodaler#21]
Hi 
I am using pretrained lstmA3 model. After loading the model successfully and obtaining the dataloader, i am trying to evaluate the model on MSCOCO. I have followed the steps as mentioned in the documentation. However there seems to be some problem with it. Here is the screenshot of the same - 
`from xmodaler.evaluation.coco_evaler import COCOEvaler
evaluator = COCOEvaler(cfg, annfile="/content/captions_val2014.json", output_dir="/content/outputs")
print(type(dataloader))
model.eval()
with torch.no_grad():
  for batch in dataloader:
    print(batch[0].keys())
    print(batch[0]["ATTRIBUTE"].shape)
    output = model(batch)
    break`
![image](https://user-images.githubusercontent.com/52096846/134625326-e5f859ec-b39c-4029-bd73-dd793f070989.png)

I am able to obtain the dataloader from build_xmodaler_valtest_loader. A batch of this loader contains list of dictionaries.

**Comment by winnechan** [comment]
Hi, the dataloader only produces a list of samples (elements of Type Dict, cannot be accessed directly by key of Type Str), you should convert the list of samples into a new dictionary instance (values of Type Tensor) to access the content via key, by calling the function `preprocess_batch` implemented in the corresponding encoder-decoder model: 

https://github.com/YehLi/xmodaler/blob/8a813bf1f4d460bac9e7853c1cba0ed78b83f741/xmodaler/modeling/meta_arch/base_enc_dec.py#L90

**Comment by architlatkar27** [comment]
Hi, according to your reply, i passed the input batch through the preprocess_batch function. It solved the error mentioned but threw a new error attached below - 
![image](https://user-images.githubusercontent.com/52096846/134854626-bace265e-6b86-40ee-90aa-0f0d2ceee088.png)
I have listed the keys in the batch dictionary after running preprocess followed by the error that it is missing G_TOKENS_IDS

**Comment by winnechan** [comment]
@architlatkar27 Hi, in our implementation of class DefaultTrainer has warpped the evaluation process as follows. 
Specifically, in evaluation, the instance of DefaultTrainer will call the function `test` at the very beginning:
https://github.com/YehLi/xmodaler/blob/8a813bf1f4d460bac9e7853c1cba0ed78b83f741/xmodaler/engine/defaults.py#L462
Then, the model will process the data from dataloader in generation mode by forwarding it to the model in the following way:
https://github.com/YehLi/xmodaler/blob/8a813bf1f4d460bac9e7853c1cba0ed78b83f741/xmodaler/engine/defaults.py#L471
Finally, the corresponding encoder-decoder model will feed the data into greedy decoder or beam search decoder instead of into the function `def _forward`:
https://github.com/YehLi/xmodaler/blob/8a813bf1f4d460bac9e7853c1cba0ed78b83f741/xmodaler/modeling/meta_arch/base_enc_dec.py#L78

In your case, you may simply rewrite `model.forward(b)` to `model(b, use_beam_search=True, output_sents=True)` and custom the decoding schema with the config key `DECODE_STRATEGY.BEAM_SIZE`.

**Comment by architlatkar27** [comment]
Hi, according to your suggestion, i was finally able to get outputs from the model. I tried the COCOEvaler but it threw the following error - 
![image](https://user-images.githubusercontent.com/52096846/135044552-3737c302-6acc-4414-ba1a-8a1bcef4aa82.png)
What changes can i make here to get the evaluation?
Also, is there any way i can evaluate it on individual images?

**Comment by jianjieluo** [comment]
Closed due to inactivity.
